### ISSUE TITLE
2048 crypto

### ISSUE THREAD

**Issue by Antonov101** [Marmik2003/CryptoJuggle#2]
Hey, I need your help, it's about Project 2048, how can I contact you?

**Comment by Marmik2003** [comment]
Hello,
I am available on https://thedataboy.com

**Comment by Antonov101** [comment]
Damn, I thought I could write to linkedin, but it's blocked in my country xD, maybe you have telegram?

**Comment by Marmik2003** [comment]
Ok, no worries, If you have any issue related to this project, issues section is dedicated to it.
You can write any issue here.
Thank you

**Comment by Antonov101** [comment]
Great, I'll tell you now:
2048 short tk:
There is an X token that has already been launched on BSC
We need to make 2048 on the blockchain, like 2048 bitcoin from back in 2014, but slightly improved
A person goes to the game page, connects via a metamask
Each wallet has either 1 attempt per day, or 3 free attempts, after which, if he scores n points, n tokens X fall on his balance, and when he wants, he can seal them
The total amount of all points scored for all games for each acc must also be considered, and if he scored the required amount, it becomes available to him to seal the nft
If the user has run out of free attempts, then he can start playing for a fee, the money will be debited from the balance, if there are none on the balance, then he can replenish the balance with X tokens
(It may be easier to make all users the same balance, for example 75 coins, and 1 game costs 25 coins, then there will be no need to be wise, or if with 1 game per day, then all active wallets will drop +25 coins per day)
2048 standard, with the usual animations, points counters, also added a button for authorization, balance, and account logout, well, the plates needed to unlock points and its current number of points)

What is there at the moment, since I'm completely 0 in this, I managed to create only a page with the 2048 game itself (without animation), the points scored in the current game are counted, and authorization via Metamask and the display of the user's wallet address is added, I transferred all the information to the server that stands on Moralis, in general, I need to implement it somehow, I don't have it yet, I would like to know the complexity of such work and possibly the cost, and also would like to know how I can put the number of user points per game and the total number of points in the database, so that I can understand later, to whom you can claim, and who doesn't...
in general, you already have a cool version and I think you could help me improve it a little. (not free)
